output "vpc_id" {
  value = "${module.vpc-exemplo.vpc_id}"
}

output "rtb_id" {
  value = "${module.vpc-exemplo.rtb_id}"
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = "${module.k8s-cluster.cluster_endpoint}"
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = "${module.k8s-cluster.kubeconfig}"
}
